name: {{#snakeCase}}{{name}}{{/snakeCase}}
description: Flutter application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ui

  # logic
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  path: ^1.8.0

  # services
  get_it: ^7.2.0
  intl: ^0.17.0
  auto_route: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # testing
  bloc_test: ^8.1.0
  mocktail: ^0.1.4

  # generation
  build_runner: ^2.1.1
  auto_route_generator: ^2.1.0
  
  # linting
  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true
  generate: true