name: {{name.snakeCase()}}
description: Flutter application
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.3

  # logic
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  path: ^1.8.1
  intl: ^0.17.0
  dartz: ^0.10.1

  # services
  get_it: ^7.2.0
  auto_route: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # testing
  bloc_test: ^9.0.3
  mocktail: ^0.3.0

  # generation
  build_runner: ^2.1.8
  auto_route_generator: ^3.2.3
  
  # linting
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  generate: true